In [0]:
sc

In [0]:
spark

In [0]:
dbutils.fs.ls("/FileStore/shared_uploads/")

Out[4]: [FileInfo(path='dbfs:/FileStore/shared_uploads/vismayabalan2239@outlook.com/', name='vismayabalan2239@outlook.com/', size=0, modificationTime=0)]

In [0]:
dbutils.fs.ls("dbfs:/FileStore/shared_uploads/vismayabalan2239@outlook.com")

Out[7]: [FileInfo(path='dbfs:/FileStore/shared_uploads/vismayabalan2239@outlook.com/sales_data_sample.csv', name='sales_data_sample.csv', size=527958, modificationTime=1727091350000)]

In [0]:
# dbutils.library.install('library_name')

In [0]:
# dbutils.notebook.run("name of another notebook")

In [0]:
dbutils.fs.rm("dbfs:/FileStore/shared_uploads/vismayabalan2239@outlook.com/sales_data_sample.csv")

In [0]:
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("SparkStreaming").getOrCreate()

In [0]:
spark

In [0]:
sales_df = spark.read.csv("dbfs:///FileStore/shared_uploads/vismayabalan2239@outlook.com/sales_data_sample.csv", inferSchema=True,header= True)

In [0]:
sales_df.toPandas().head()

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,QTR_ID,MONTH_ID,YEAR_ID,...,ADDRESSLINE1,ADDRESSLINE2,CITY,STATE,POSTALCODE,COUNTRY,TERRITORY,CONTACTLASTNAME,CONTACTFIRSTNAME,DEALSIZE
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,1,2,2003,...,897 Long Airport Avenue,None,NYC,NY,10022,USA,NA,Yu,Kwai,Small
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,2,5,2003,...,59 rue de l'Abbaye,None,Reims,None,51100,France,EMEA,Henriot,Paul,Small
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,3,7,2003,...,27 rue du Colonel Pierre Avia,None,Paris,None,75508,France,EMEA,Da Cunha,Daniel,Medium
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,3,8,2003,...,78934 Hillside Dr.,None,Pasadena,CA,90003,USA,NA,Young,Julie,Medium
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,4,10,2003,...,7734 Strong St.,None,San Francisco,CA,None,USA,NA,Brown,Julie,Medium

In [0]:
sales_df.schema

Out[13]: StructType([StructField('ORDERNUMBER', IntegerType(), True), StructField('QUANTITYORDERED', IntegerType(), True), StructField('PRICEEACH', DoubleType(), True), StructField('ORDERLINENUMBER', IntegerType(), True), StructField('SALES', DoubleType(), True), StructField('ORDERDATE', StringType(), True), StructField('STATUS', StringType(), True), StructField('QTR_ID', IntegerType(), True), StructField('MONTH_ID', IntegerType(), True), StructField('YEAR_ID', IntegerType(), True), StructField('PRODUCTLINE', StringType(), True), StructField('MSRP', IntegerType(), True), StructField('PRODUCTCODE', StringType(), True), StructField('CUSTOMERNAME', StringType(), True), StructField('PHONE', StringType(), True), StructField('ADDRESSLINE1', StringType(), True), StructField('ADDRESSLINE2', StringType(), True), StructField('CITY', StringType(), True), StructField('STATE', StringType(), True), StructField('POSTALCODE', StringType(), True), StructField('COUNTRY', StringType(), True), StructField('TERRITORY', StringType(), True), StructField('CONTACTLASTNAME', StringType(), True), StructField('CONTACTFIRSTNAME', StringType(), True), StructField('DEALSIZE', StringType(), True)])

In [0]:
from pyspark.sql.types import *

schema = StructType([
StructField('ORDERNUMBER', IntegerType(), True), 
StructField('QUANTITYORDERED', IntegerType(), True), 
StructField('PRICEEACH', DoubleType(), True), 
StructField('ORDERLINENUMBER', IntegerType(), True), 
StructField('SALES', DoubleType(), True), 
StructField('ORDERDATE', StringType(), True), 
StructField('STATUS', StringType(), True), 
StructField('QTR_ID', IntegerType(), True), 
StructField('MONTH_ID', IntegerType(), True), 
StructField('YEAR_ID', IntegerType(), True), 
StructField('PRODUCTLINE', StringType(), True), 
StructField('MSRP', IntegerType(), True), 
StructField('PRODUCTCODE', StringType(), True), 
StructField('CUSTOMERNAME', StringType(), True), 
StructField('PHONE', StringType(), True), 
StructField('ADDRESSLINE1', StringType(), True), 
StructField('ADDRESSLINE2', StringType(), True), 
StructField('CITY', StringType(), True), 
StructField('STATE', StringType(), True), 
StructField('POSTALCODE', StringType(), True), 
StructField('COUNTRY', StringType(), True), 
StructField('TERRITORY', StringType(), True), 
StructField('CONTACTLASTNAME', StringType(), True), 
StructField('CONTACTFIRSTNAME', StringType(), True), 
StructField('DEALSIZE', StringType(), True)])

In [0]:
sales_df = spark.readStream.option("sep",",")\
                .option("header","true") \
                .schema(schema) \
                .csv("dbfs:///FileStore/shared_uploads/vismayabalan2239@outlook.com/sales_data_sample.csv")

In [0]:
sales_df.groupBy('PRODUCTLINE').value()

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
File <command-365574726611520>:1
----> 1 sales_df.groupBy('PRODUCTLINE').valuecount()

AttributeError: 'GroupedData' object has no attribute 'valuecount'